name: Build LaTeX PDF for PRs and Branches

on:
  push:
    branches:
      - '**'  # run on all branches
  pull_request:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout all files
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install TeX Live Full
      - name: Install TeX Live Full
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      # 3. Create output folder
      - name: Prepare docs folder
        run: mkdir -p docs

      # 4. Compile PDF using pdflatex + bibtex
      - name: Compile LaTeX with pdflatex
        run: |
          pdflatex -interaction=nonstopmode -output-directory=docs main.tex
          bibtex docs/main
          pdflatex -interaction=nonstopmode -output-directory=docs main.tex
          pdflatex -interaction=nonstopmode -output-directory=docs main.tex

      # 5. Set artifact name based on branch or PR
      - name: Set artifact name
        id: vars
        run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then
            ART_NAME="PDF-${GITHUB_HEAD_REF}"
          else
            ART_NAME="PDF-${GITHUB_REF_NAME}"
          fi
          echo "ARTIFACT_NAME=$ART_NAME" >> $GITHUB_ENV

      # 6. Upload the compiled PDF as artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: docs/main.pdf

      # 7. Upload all LaTeX source files as artifact
      - name: Upload LaTeX sources
        uses: actions/upload-artifact@v4
        with:
          name: Sources-${{ env.ARTIFACT_NAME }}
          path: |
            ./**/*.tex
            ./**/*.cls
            ./**/*.sty
            ./**/*.bib
            ./**/*.bst
            ./img/**
            ./figs/**
            ./images/**
            ./figures/**

      # 8. Push compiled PDF to GitHub Pages branch
      - name: Deploy PDF to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          cp docs/main.pdf main.pdf
          git add main.pdf
          git commit -m "Update compiled PDF from workflow"
          git push -f origin gh-pages
