name: Build LaTeX PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: scheme-full

      - name: Compile LaTeX document
        run: |
          mkdir -p docs
          latexmk -pdf -interaction=nonstopmode -output-directory=docs example.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: docs/example.pdf
